name: CI
on: pull_request
jobs:
  mustpass:
    name: this must pass
    runs-on: ubuntu-latest
    steps:
      - name: this will pass
        run: |
          echo "this will pass"
          true
  mayfail:
    name: this may fail
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: this may fail
        run: |
         echo "this may fail"
          false
      - name: notify
        if: ${{ failure() }}
        run: |
          echo "but we're happy anyway"
      - name: notifysuccess
        if: ${{ success() }}
        run: |
          echo "but it succeeded somehow"
