name: CI
on: pull_request
jobs:
  mustpass:
    name: this must pass
    runs-on: ubuntu-latest
    steps:
      - name: this will pass
        run: |
          echo "this will pass"
          true
  mayfail:
    name: this may fail
    runs-on: ubuntu-latest
    outputs:
      passed: ${{steps.dothetest.outputs.passed}}
      details: ${{steps.savetheurl.outputs.details}}
    steps:
      - id: dothetest
        name: this may fail
        continue-on-error: true
        run: |
          echo "this may fail"
          false
          echo "::set-output name=passed::true"
      - id: savetheurl
        name: save check URL
        run: |
          CHECK_SUITE_URL=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq -r '.check_suite_url')
          CHECK_RUN_URL=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" $CHECK_SUITE_URL/check-runs | jq -r '.check_runs[] | select(.name=="this may fail") | .html_url')
          echo "::set-output name=details::$CHECK_RUN_URL"
  evaluate:
    name: evaluate the previous step
    runs-on: ubuntu-latest
    needs: mayfail
    steps:
      - if: ${{ needs.mayfail.outputs.passed == 'true' }}
        uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ":checkered_flag: Passed"
          check_for_duplicate_msg: false
      - if: ${{ needs.mayfail.outputs.passed != 'true' }}
        uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            :hand: Failed

            - [ ] Please check the [output](${{needs.mayfail.outputs.details}}) to see if this is a new problem
          check_for_duplicate_msg: false
