name: CI
on: pull_request
jobs:
  mustpass:
    name: this must pass
    runs-on: ubuntu-latest
    steps:
      - name: this will pass
        run: |
          echo "this will pass"
          true
  mayfail:
    name: this may fail
    runs-on: ubuntu-latest
    outputs:
      passed: ${{steps.dothetest.outputs.passed}}
    steps:
      - id: dothetest
        name: this may fail
        continue-on-error: true
        run: |
          echo "this may fail"
          false
          echo "::set-output name=passed::true"
  evaluate:
    name: evaluate the previous step
    runs-on: ubuntu-latest
    needs: mayfail
    steps:
      - if: ${{ needs.mayfail.outputs.passed == 'true' }}
        uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ":checkered_flag: Passed"
          check_for_duplicate_msg: false
      - if: ${{ needs.mayfail.outputs.passed != 'true' }}
        uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            :hand: Failed

            - [ ] Please check the [output](checks?check_run_id=${{github.run_id}}) to see if this is a new problem
          check_for_duplicate_msg: false
