name: System status check

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

jobs:
  mayfail:
    runs-on: ubuntu-latest
    steps:
      - name: Run the test
        run: |
          echo "Starting test"
          true
      - name: Report the results
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status() }}
