name: System status check
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  mayfail:
    runs-on: ubuntu-latest
    steps:
      - name: Run the test
        run: |
          echo "Starting test"
          if (( RANDOM % 2 == 0 )); then true; else false; fi
      - uses: act10ns/slack@v1
        name: Report the results
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
